version: '3.7'

services:

  elasticsearch:
    build:
      context: containers/elasticsearch/
      args:
        ELASTIC_VERSION: 7.6.0
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      xpack.security.enabled: "true"
    networks:
      - elk
    restart: on-failure
    env_file:
     - ./environment_variables 
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        
  logstash:
    build:
      context: containers/logstash/
      args:
        ELASTIC_VERSION: 7.6.0
    volumes:
      - ./data-inputs/netflow:/data_inputs/netflow/
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
      PYTHONIOENCODING: "UTF-8"
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: on-failure
    env_file:
     - ./environment_variables  
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        
  kibana:
    build:
      context: containers/kibana/
      args:
        ELASTIC_VERSION: 7.6.0
    ports:
      - "80:5601"
    networks:
      - elk
    restart: on-failure
    depends_on:
      - elasticsearch
    env_file:
     - ./environment_variables 
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        
  evtx-input:
    build:
      context: containers/input-modules/evtx
    volumes:
      - ./data-inputs/evtx:/data_inputs/evtx
    restart: on-failure
    env_file:
      - ./environment_variables
    networks:
      - elk
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"  
                
  syslog-input:
    build:
      context: containers/input-modules/syslog
      args:
        ELASTIC_VERSION: 7.6.0
    volumes:
      - ./data-inputs/syslog:/data_inputs/syslog
      - ./data-inputs/auth:/data_inputs/auth
    networks:
      - elk
    restart: on-failure
    depends_on:
      - kibana
    env_file:
     - ./environment_variables  
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        
  auditd-input:
    build:
      context: containers/input-modules/auditd
      args:
        ELASTIC_VERSION: 7.6.0
    volumes:
      - ./data-inputs/auditd:/data_inputs/auditd
    networks:
      - elk
    restart: on-failure
    depends_on:
      - kibana
    env_file:
     - ./environment_variables  
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        
  nessus-input:
    build:
      context: containers/input-modules/nessus
      args:
        ELASTIC_VERSION: 7.6.0
    volumes:
      - ./data-inputs/nessus:/data_inputs/nessus
    restart: on-failure
    networks:
      - elk
    depends_on:
      - kibana
    env_file:
     - ./environment_variables
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"  
  
  netflow-input:
    build:
      context: containers/input-modules/netflow
    volumes:
      - ./data-inputs/netflow:/data_inputs/netflow
    restart: on-failure
    env_file:
      - ./environment_variables
    networks:
      - elk
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  network-config-input:
    build:
      context: containers/input-modules/network-configs
    volumes:
      - ./data-inputs/network-configs:/data_inputs/network-configs
    restart: on-failure
    env_file:
      - ./environment_variables
    networks:
      - elk
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"        
        
  jupyter:
    build:
      context: containers/jupyter
    command: start.sh jupyter lab --LabApp.token=''
    volumes:
      - notebooks:/home/jovyan/
      - alerts:/home/jovyan/alerts
    ports:
      - "8888:8888"
    restart: on-failure
    env_file:
      - ./environment_variables
    networks:
      - elk
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"  

  elastalert:
    build:
      context: containers/elastalert
    volumes:
      - alerts:/alerts
    restart: on-failure
    env_file:
      - ./environment_variables
    networks:
      - elk
    depends_on:
      - elasticsearch
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        
  input-module-cleanup:
    build:
      context: containers/input-modules/cleanup
    volumes:
      - ./data-inputs:/data_inputs
    restart: on-failure
    env_file:
      - ./environment_variables
    networks:
      - elk
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        
  # Short-lived container to set up elastic environment
  setup:
    build:
      context: containers/setup
    env_file:
      - ./environment_variables
    networks:
      - elk
    depends_on: 
       - elasticsearch     
networks:
  elk:
    driver: bridge
    
volumes:
  alerts:
    driver: local
    driver_opts:
      type: none
      device: $PWD/alerts
      o: bind  
      
  notebooks:
    driver: local
    driver_opts:
      type: none
      device: $PWD/notebooks
      o: bind